/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Titanium SDK
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.youtubeplayer;

import android.webkit.WebView;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

@Kroll.module(name="TiYoutubeplayer", id="ti.youtubeplayer")
public class TiYoutubePlayerModule extends KrollModule {

	private static final String TAG = "TiYoutubeplayerModule";

	public TiYoutubePlayerModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		// Module initialization if needed
        WebView.setWebContentsDebuggingEnabled(true);
    }

	@Override
	public String getApiName() {
		return "Ti.YoutubePlayer";
	}

	@Kroll.method
	public PlayerViewProxy createPlayerView(@Kroll.argument(optional = true) Object args) {
		PlayerViewProxy proxy = new PlayerViewProxy();

		if (args != null) {
			proxy.handleCreationArgs(this, new Object[] { args });
		}

		return proxy;
	}
}
