/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Titanium SDK
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.youtubeplayer;

import android.webkit.WebView;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

@Kroll.module(name="TiYoutubeplayer", id="ti.youtubeplayer")
public class TiYoutubePlayerModule extends KrollModule {

	private static final String TAG = "TiYoutubeplayerModule";

	@Kroll.constant
	public static final int SCALING_ASPECT_FIT = 0;

	@Kroll.constant
	public static final int SCALING_ASPECT_FILL = 1;

	@Kroll.constant
	public static final String PLAYBACK_QUALITY_SMALL = "small";

	@Kroll.constant
	public static final String PLAYBACK_QUALITY_MEDIUM = "medium";

	@Kroll.constant
	public static final String PLAYBACK_QUALITY_LARGE = "large";

	@Kroll.constant
	public static final String PLAYBACK_QUALITY_HD720 = "hd720";

	@Kroll.constant
	public static final String PLAYBACK_QUALITY_HD1080 = "hd1080";

	@Kroll.constant
	public static final String PLAYBACK_QUALITY_HIGH_RESOLUTION = "highres";

	@Kroll.constant
	public static final String PLAYBACK_QUALITY_AUTO = "auto";

	public TiYoutubePlayerModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		// Remote WebView inspection affects every WebView in the host app, so it
		// must never be on in a production build.
		if (app != null && app.getDeployType() != null
				&& !TiApplication.DEPLOY_TYPE_PRODUCTION.equals(app.getDeployType())) {
			WebView.setWebContentsDebuggingEnabled(true);
		}
    }

	@Override
	public String getApiName() {
		return "Ti.YoutubePlayer";
	}

	@Kroll.method
	public PlayerViewProxy createPlayerView(@Kroll.argument(optional = true) Object args) {
		PlayerViewProxy proxy = new PlayerViewProxy();

		if (args != null) {
			proxy.handleCreationArgs(this, new Object[] { args });
		}

		return proxy;
	}
}
